In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
y = np.array([0,0,1,0,1,0,0,0,0,0,1,1,1,0,1,0,1,1,1,1])

In [6]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2) #shuffel = False, random_state=5

In [7]:
x_train

array([ 2,  1,  4, 11, 13,  5,  9,  3, 20, 12, 19, 10, 15, 16, 17, 14])

In [8]:
x_test

array([ 7,  8, 18,  6])

In [9]:
y_train

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0])

In [10]:
y_test

array([0, 0, 1, 0])